services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - localization_net

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - backend_static:/app/static
      - backend_media:/app/media
    networks:
      - localization_net

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - localization_net

  proxy:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - backend_static:/var/www/static:ro
      - backend_media:/var/www/media:ro
    networks:
      - localization_net

volumes:
  db_data:
  backend_static:
  backend_media:


networks:
  localization_net:
    driver: bridge
    name: localization_net
    ipam:
      config:
        - subnet: 172.31.0.0/16
